### ISSUE TITLE
Translated version (English)

### ISSUE THREAD

**Issue by HalfBloodprinc3** [Ruan625Br/FileManagerSphere#1]
Can you please build a Translated version of this help,then it becomes easy for us users to interact with this app in a more efficient way.

**Comment by IzzySoft** [comment]
Guess you could take the [Portuguese `strings.xml`](https://github.com/Ruan625Br/FileManagerSphere/blob/master/app/src/main/res/values-pt-rBR/strings.xml) to translate its values (DeepL.com can be a good help with that), then attach your edited version here (or open a PR adding it as `app/src/main/res/values/strings.xml` directly), if @Ruan625Br accepts that? After all it's FOSS – and this kind of contribution can be done without knowing how to code :wink:

**Comment by Ruan625Br** [comment]
Thanks for your feedback! We are committed to providing a better user experience for our global community. We have already started the process of translating the app into multiple languages, including English, to make it easier for users around the world to efficiently interact with the app.

The translation effort is ongoing and we are continually working to improve and expand the available translations. With the help of contributors, we are constantly making progress to ensure our app is accessible to as many users as possible.

We appreciate your support and understanding as we strive to create a more inclusive and user-friendly experience for everyone. If you have any further suggestions or comments, please feel free to share them with us. Your opinion is valuable to help us improve our app and make it even better for all users.

**Comment by OsitoGrande** [comment]
How would you like translation contributions to be received by you?

**Comment by Ruan625Br** [comment]
Thank you @OsitoGrande  for your interest in contributing translations! You can start translating our FileManagerSphere application into Weblate by following this link: [Translate FileManagerSphere](https://hosted.weblate.org/engage/filemanagersphere/)

We look forward to your valuable contributions to make our app accessible to users all over the world. Happy translation!

**Comment by IzzySoft** [comment]
> You can start translating our FileManagerSphere application into Weblate

Thanks for that pointer! Included it with the listing of your app with my repo, so that link will show up in the F-Droid client, so more users might find it.

**Comment by OsitoGrande** [comment]
> Thank you @OsitoGrande for your interest in contributing translations! You can start translating our FileManagerSphere application into Weblate by following this link: [Translate FileManagerSphere](https://hosted.weblate.org/engage/filemanagersphere/)
> 
> We look forward to your valuable contributions to make our app accessible to users all over the world. Happy translation!

Thanks for the info. I'll start looking at the English translation next week. w/c 24/07/23

**Comment by OsitoGrande** [comment]
Ive been looking at the English translation over the last couple of weeks, there's a couple of queries I have regarding language/grammar used etc. Is it best to ask here or contact you directly?

**Comment by Ruan625Br** [comment]
Certainly, @OsitoGrande! Your interest in refining the English translation is much appreciated. Your dedication to proofreading and enhancing the language and grammar is commendable.

If you have any inquiries or suggestions regarding the language or grammar utilized in the translation, we kindly request you to share them within this `GitHub issue`. By doing so, we can maintain a transparent log of conversations and effectively collaborate as a team. Should you come across specific examples or identify areas that warrant improvement, please don't hesitate to highlight them.

For more intricate or extensive matters, should they arise, feel free to reach out to me directly via [telegram](t.me/JuanNascimento).

I'd like to mention that the `FileManagerSphere `translations are presently hosted on `Weblate`. Regrettably, the project's approval for complimentary use of `Weblate `is pending. Given that `FileManagerSphere` doesn't generate `profits`, accommodating a translation platform poses financial challenges.

Thank you again for your valuable contributions. Looking forward to the collaboration ahead!
