### ISSUE TITLE
Android 11+ support

### ISSUE THREAD

**Issue by abodinagdat16** [Ruan625Br/FileManagerSphere#14]
Your app not working on android 11+ .....
or i can say not requesting to access files .....you can set target sdk to 26 or 28 and will work on android 11+ devices but if you share your app on Google play use new request ways     ......

**Comment by Ruan625Br** [comment]
It is difficult for me to know why this error occurs, all versions are tested on **android 13**, if you can provide more information I will be grateful

**Comment by abodinagdat16** [comment]
see this:
![Screenshot_2023-07-28-23-35-58-607_com google android permissioncontroller](https://github.com/Ruan625Br/FileManagerSphere/assets/69758268/35c6ac6d-1e61-47f6-8bb8-1d7ece58954d)

**Comment by Ruan625Br** [comment]
what is your android version ?

**Comment by Ruan625Br** [comment]
``you can set target sdk to 26 or 28 and will work on android 11+ `` regarding this, the target SDK is currently **33**

**Comment by Ruan625Br** [comment]
@abodinagdat16 I don't think the change I made to the code will resolve the error, but try downloading the debug app from [github actions](https://github.com/Ruan625Br/FileManagerSphere/actions/runs/5696410711), but I don't think this is the solution

**Comment by abodinagdat16** [comment]
Also not working i tried it .... you must set `Target Sdk`to 26 or 28 because when you set the target sdk to 29+ 
`android.permission.READ_EXTERNAL_STORAGE` 
will not be requested 😬.

**Comment by abodinagdat16** [comment]
As long as you didn't upload it to the Google Play Store, you can set target sdk to 26 or 28.

**Comment by Ruan625Br** [comment]
It is difficult to understand this error, for android 11+ I use the promise `android.permission.MANAGE_EXTERNAL_STORAGE`

**Comment by abodinagdat16** [comment]
Ok ....if you want i can help you to develop your app ..i can add zip viewer or dex decompiler and fixing this issue for you but before that give me your telegram user name .....

**Comment by Ruan625Br** [comment]
[JuanNascimento](https://t.me/JuanNascimento)

**Comment by abodinagdat16** [comment]
Requested after clicking on storage option
