### ISSUE TITLE
adicionar suporte ou reconhecimento para o armazenamento externo (Cartão SD)

### ISSUE THREAD

**Issue by JonatasVi** [Ruan625Br/FileManagerSphere#15]
Seria interessante se reconhecesse também o armazenamento externo e não so o interno

**Comment by Ruan625Br** [comment]
Olá @JonatasVi ! O FileManagerSphere ainda está em seus estágios iniciais, com pouco mais de um mês de desenvolvimento. No entanto, não se preocupe, em versões futuras, será adicionado suporte para `Cartão SD` . Fique atento às atualizações para desfrutar de recursos ainda mais extensos!
