### ISSUE TITLE
Fastlane

### ISSUE THREAD

**Issue by IzzySoft** [Ruan625Br/FileManagerSphere#2]
First thanks for making your app available using a FOSS license :trophy: And even use Fastlane for descriptions and graphics! Some point on the latter: it lacks the (mandatory) `en-US`. As the current structures only hold graphics (and no description yet), may I suggest renaming `fastlane/metadata/android/pt-BR` to  `fastlane/metadata/android/en-US` (as `en-US` is always the fall-back for missing locales, they'd be shown for all of them then), and add a `short_description.txt` plus `full_description.txt`? For example:

* short desc: "your personalized file manager"
* (short desc for `pt-BR, if you want: "seu gerenciador de arquivos personalizado")
* full desc:

```html
<p><i>FileManagerSphere</i> is a powerful file management tool designed to simplify and enhance your experience when dealing with documents, media and other file types. With advanced features and an intuitive interface, <i>FileManagerSphere</i> offers a comprehensive solution to organize, navigate, search and manipulate your files with ease.</p>
<p>Please note that <i>FileManagerSphere</i> is still under construction. It currently supports only Portuguese locale, but (with your help) it will grow and widen its support.</p>
```

Maybe add a little section to the Readme on how to support you with other locales then (see #1). Thanks in advance!

**Comment by Ruan625Br** [comment]
We appreciate your kind words and your interest in our FileManagerSphere app!

We welcome your suggestion regarding Fastlane descriptions and graphics with gratitude. We will include the en-US folder with the short_description.txt and full_description.txt files, ensuring that all locales without specific descriptions have a default en-US option, making them more comprehensive for users.

Additionally, we've already included a section in the Readme explaining how users can contribute to support other locales.

Again, we appreciate your input and are excited to see the progress of the app's internationalization. If you have any further suggestions or questions, please do not hesitate to let us know. Thanks in advance for your support!

**Comment by IzzySoft** [comment]
Thanks! Can you please give me a ping when the Fastlane folder was updated – so I can update my configuration here to fetch it with each new release?

Oh, I didn't specify: I'm talking about [the listing here](https://apt.izzysoft.de/packages/com.etb.filemanager/) (and you're welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your Readme).

**Comment by Ruan625Br** [comment]
Good news! The Fastlane folder has been updated successfully. Now, you can easily update your configuration accordingly.

Additionally, I've added a badge to my Readme, providing convenient access to my app's listing. Thanks for the sugestion! If you have further requests or questions, please don't hesitate to get in touch. I am here to help!

**Comment by IzzySoft** [comment]
> Good news! The Fastlane folder has been updated successfully. Now, you can easily update your configuration accordingly.

Thanks! It needs a little fixing, though:

* `short_description.txt` is limited to 80 chars – everything beyond that will simply cut off. Suggestion: `make organizing, browsing and manipulating documents and media more efficient` (the name already implies it is a file manager, the screenshots cover the material design).

I've enabled everything else already now, so (except for the short description) it will be pulled along with future releases. Once shortdesc is fixed, I'll add that, too – and should you then wish an immediate refresh at my end, I can manually trigger that.

> I've added a badge to my Readme, providing convenient access to my app's listing.

Nice, thanks! Both even :smiley:

> If you have further requests or questions, please don't hesitate to get in touch. I am here to help!

Thanks a lot! Once you think it would be ready for listing at F-Droid.org (the more prestigious place, but also with stricter rules, which I think your app is meeting), let me know and I gladly assist you with that. I'd suggest to wait a little with that until at least full English support has been implemented with your app.

**Comment by Ruan625Br** [comment]
Thank you for your comment on the 80 character limitation of **short_description.txt**. The file has been updated to adhere to the specified limit.

Once again, thank you for your cooperation and responsiveness. I look forward to our continued collaboration,
If you have further requests or questions please don't hesitate to get in touch. I am here to help!

**Comment by IzzySoft** [comment]
Thanks for the update! Seems to be at 82 chars now (at least the size says 82 bytes, and I see no "special chars"). So the trailing dot might be truncated, which is no big issue. To make sure all is carried over, I'd remove that trailing dot – and the comma before the "and" :wink:

Thanks once more for your swift reactions and actions, much appreciated! I've meanwhile fully enabled all fastlane features currently present. Should you one day add others (like a featureGraphic, or per-release changelogs), my monthly "wuality check task" should inform me (you can of course also ping me before my bot does, so I enable those then).

All the best for you and the project then! If you have any questions, just reach out, I'll do what I can to answer them.

**Comment by Ruan625Br** [comment]
Hello,

I have exciting news! I'm planning to release [FileManagerSphere ](https://github.com/Ruan625Br/FileManagerSphere) on fdroid in the next version. However, I'm new to app publishing and I need some guidance. Specifically, I would like your help. About the [metadata ](https://drive.google.com/file/d/15fpWYgKu-OfSN-2ptGsVo0OZSrBcGEY9/view?usp=drive_link)file, I created it for learning purposes, just to understand how it works.

Your assistance and expertise in app publishing will be highly appreciated. I await your response!

Thanks.

**Comment by IzzySoft** [comment]
While I'm not going to check Google Drive (the Metadata file should be small enough to quote it here :wink:), let me point you to my relevant articles on that. There's a section on [getting your app to F-Droid](https://android.izzysoft.de/articles/named/fdroid-intro-2?lang=en#rfp), and for more details on Metadata you can [find some hints here](https://android.izzysoft.de/articles/named/fdroid-simple-binary-repo?lang=en#feeding). Quoting the head from your app in my repo (which can be used at F-Droid.org, too):

```yaml
Categories:
  - System
License: GPL-3.0-or-later
AuthorName: Juan Nascimento
SourceCode: https://github.com/Ruan625Br/FileManagerSphere
IssueTracker: https://github.com/Ruan625Br/FileManagerSphere/issues
Translation: https://hosted.weblate.org/engage/filemanagersphere/
Changelog: https://github.com/Ruan625Br/FileManagerSphere/releases

AutoName: FileManagerSphere

RepoType: git
Repo: https://github.com/Ruan625Br/FileManagerSphere

Builds:
  - versionName: '1.0'
    versionCode: 1
    commit: v1.0
    subdir: app
    gradle:
      - yes

AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: '1.0'
CurrentVersionCode: 1
```

I've also amended the build block you'd need for F-Droid.org (missing in my repo as I don't build the APKs myself – but this being a Kotlin app, it should be quite straight-forward).

**Comment by Ruan625Br** [comment]
Thanks I read the section on [how to bring your app to F-Droid](https://android.izzysoft.de/articles/named/fdroid-intro-2?lang=en#rfp) and created [my request for packaging](https://gitlab.com/fdroid/rfp/-/issues/2486)

**Comment by IzzySoft** [comment]
Any reason for making that request confidential? I took the freedom to copy over the YAML I've provided above meanwhile. Would prefer removing the "confidential" flag from the RFP, as we process those issues in the open usually :wink:

**Comment by Ruan625Br** [comment]
Hello @IzzySoft, I have a doubt, for me to launch a new update of my app on f-droid it is necessary to create a new packaging request?

**Comment by IzzySoft** [comment]
For an update? Why? Did the `applicationId` change? RFPs are only needed for listing apps not yet there. From your app's YAML:

```yaml
AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: 1.1.1
CurrentVersionCode: 3
```

AutoUpdate is enabled, so all you'd need to do is creating a new release/tag here and F-Droid's CheckUpdates should fetch it on its next run.

**Comment by Ruan625Br** [comment]
Oh I understand, thank you very much
