### ISSUE TITLE
Multi-file Copy + Paste force close/crash

### ISSUE THREAD

**Issue by OsitoGrande** [Ruan625Br/FileManagerSphere#27]
When selecting two files in one directory and attempting to paste them back into the same directory, this action causes immediate closure of app. App will not re-open on first attempt but will re-open on second attempt.

**Comment by Ruan625Br** [comment]
Hello @OsitoGrande , this error has already been fixed, but thanks for the warning

**Comment by OsitoGrande** [comment]
Excellent! Thanks for the update. 👍🏼
