### ISSUE TITLE
Unable to access some folders

### ISSUE THREAD

**Issue by ViktorKahu** [Ruan625Br/FileManagerSphere#35]
I am unable to access some folders that are normally accessable via the native file manager.

Error java.nio.file.AccessDeniedException: /storage/emulated/0/Android/data

All permissions have been granted.
Android 13
GrapheneOS

**Comment by Ruan625Br** [comment]
Hello @ViktorKahu, Google has recently imposed access restrictions on the "data" and "obb" folders in newer Android devices, aiming to enhance security. I regret to inform you that I am still in search of a solution to address this specific issue. Thank you for your understanding and for reporting this issue.
