### ISSUE TITLE
Permission issue & recent view

### ISSUE THREAD

**Issue by Mohammad-Azizi** [Ruan625Br/FileManagerSphere#36]
For the first time nothing works when you click on any button any layout nothing happens except internal storage,,I want you to add a permission request dialog at first when the app opens to be allowed,,,the recent view displaying half in my device fix it add scroll view

**Comment by Ruan625Br** [comment]
Hello @Mohammad-Azizi i, I am already aware of this error, but thanks for opening the issue.
