### ISSUE TITLE
Add this app to fdroid!

### ISSUE THREAD

**Issue by CodeCubeNeo** [Ruan625Br/FileManagerSphere#4]

**Comment by Ruan625Br** [comment]
Great news! FileManagerSphere is now available on F-Droid, making it easily accessible to everyone. You can check it out through the following link: [Link to FileManagerSphere on F-Droid](https://f-droid.org/app/com.etb.filemanager).

**Comment by Ruan625Br** [comment]
I've removed the readme links

**Comment by IzzySoft** [comment]
Thanks, cleaning up then here. Should you need it back one day for some reason, just "ring ma bell" :wink:
