### ISSUE TITLE
[Feature Request] Themed / Monochrome app icon support

### ISSUE THREAD

**Issue by sebastien46** [Ruan625Br/FileManagerSphere#7]
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#User_Theming

**Comment by Ruan625Br** [comment]
Olá @sebastien46 ! **FileManagerSphere** ainda está em seus estágios iniciais, com pouco mais de um mês de desenvolvimento. No entanto, não se preocupe, o suporte para `ícones adaptativos` será adicionado em versões futuras. Fique atento às atualizações para desfrutar de recursos ainda mais extensos!
